<a href="https://colab.research.google.com/github/Gururajreddy/Pytorch-Tutorial/blob/master/trainig_in_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np

In [24]:
#1 DArray
a=np.array([1,2,3,4])
print(type(a))

#2D Array
b=np.array([[1,2,3,4],[5,6,1,2]])
print(type(b))

#3D Array
c=np.array([[1,2],[3,4],[5,6],[6,8]])
print(type(c))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [14]:
from re import MULTILINE
def add(a,b):
  sum = a+b
  print(sum)

def sub(a,b):
  sub = a-b
  print(sub)

def mul(a,b):
  mul = a*b
  print(mul)

def div(a,b):
  div = a/b
  if(a/b == 0):
    print("invalid")
  else:
    print(div)

add(5,6)
sub(5,6)
mul(5,6)
div(5,1)

11
-1
30
5.0


In [63]:
def sum(n):
  n=int(input("enter the number"))
  sum=0
  while(n>0):
    sum+=n
    n-=1
    print(sum)

    

In [53]:
#dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [28]:
#np.arange
np.arange(1,11,3)

array([ 1,  4,  7, 10])

In [31]:
# with reshape(rows, column)
np.arange(1,11).reshape(2,5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [34]:
#np.onces and np.zeros
#have to provide tuple
# why use onces and zeros ans or inistalazation values
np.ones((3,4))
np.zeros((3,4))
np.random.random((3,4))


array([[0.45291316, 0.82089038, 0.4226876 , 0.65781114],
       [0.07798335, 0.61421175, 0.86397223, 0.40208599],
       [0.71247522, 0.04417502, 0.71636136, 0.47957719]])

In [37]:
#np.linspace
# linearly separate the points genrate in the given range
          #(low range,uper range,no: item to generate)
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [39]:
#np.identity
#in the identity matrix only diagonal is one and rest of them is zero
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array attributes

In [15]:
import numpy as np
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
print(a1,a2,a3)

[0 1 2 3 4 5 6 7 8 9] [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]] [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [18]:
#ndim (number of dimention)
a3.ndim

3

In [22]:
#shape , it will tell how many dimention is present
a3.shape

(2, 2, 2)

In [24]:
#size
print(a3.size)

8


In [25]:
# itemsize, it will tell you memory size
a3.size

8

Changing Datatypes

In [33]:
#astype (we can reduce the memory by reducing size and can convert the datatypes
a3.astype(np.int32)

array([[[0, 0, 1, 0],
        [2, 0, 3, 0]],

       [[4, 0, 5, 0],
        [6, 0, 7, 0]]], dtype=int32)

Array Operation

In [34]:
a1=np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [36]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [38]:
#scalar operation
# matrix mul with scalar operation
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [40]:
#relation operatior
a2>5,a2 == 15

(array([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]), array([[False, False, False,  True],
        [False, False, False, False],
        [False, False, False, False]]))

In [42]:
#vector operations
a1+a2,a1*a2,a1**a2,a1/a2

(array([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]]), array([[  0,  13,  28,  45],
        [ 64,  85, 108, 133],
        [160, 189, 220, 253]]), array([[                   0,                    1,                16384,
                     14348907],
        [          4294967296,         762939453125,      101559956668416,
            11398895185373143],
        [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
          6839173302027254275]]), array([[0.        , 0.07692308, 0.14285714, 0.2       ],
        [0.25      , 0.29411765, 0.33333333, 0.36842105],
        [0.4       , 0.42857143, 0.45454545, 0.47826087]]))